package com.softserve.edu04.hw.task3;

public enum HTTPError {
    BAD_REQUEST, UNAUTHORIZED,
    PAYMENT_REQUIRED, FORBIDDEN,
    NOT_FOUND, METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE, REQUEST_TIMEOUT,
    CONFLICT, GONE

}
